### PR TITLE
Deprecate `Logging` interface in favor of `WithLogging`

### PR DESCRIPTION
**Pull request by yevhenii-nadtochii**
This PR deprecates Java's `Logging` interface in favor of `WithLogging` Kotlin's counterpart. 

It provides the following benefits: 

1. `WithLogging` is platform-independent, just like `LoggingFactory`. It makes both library entry points multiplatform. It will allow using of them in client's multiplatform codebase. Here stems out the following restriction: the returned `logger` will NOT have an explicit type of `LoggingApi` specified anymore. It is because the common code can't know which logger (and the corresponding `LoggingApi`) will be used by the target implementations of `LoggingFactory`. We can't know it even if the library is used in a concrete target directly, for example, in JVM. 
2. Performance benefits. `Logging` interface provides shortcuts to methods of `FluentLogger.Api`. Preserving of a call-site is done via the injection, which imposes additional performance penalty. `WithLogging` doesn't redirect calls to the method of the used logger, it just exposes the logger itself.
3. `Logging` uses and exposes API of `FluentLogger`, along with their API. `WithLogging` already uses our own API.

### CODE REVIEW

**Comment by yevhenii-nadtochii** [comment]
@alexander-yevsyukov PTAL

**Review by alexander-yevsyukov — APPROVED** [review]
LGTM

**Comment by alexander-yevsyukov** [comment]
@yevhenii-nadtochii, please also suppress deprecation in `LoggingSpec`. The build emits warning in this class.

**Comment by alexander-yevsyukov** [comment]
@yevhenii-nadtochii, we also need a utility method for replacing formatting methods from Flogger. I'm currently using this version in `tool-base` and it takes a lot of replacements like this:

```java
logger().atDebug().log(() -> format("my message %s", myArg));
``` 

It would be good to have something like:

```java
logger().atDebug().log(lazyFmt("my message %s", myArg));
```

**Comment by yevhenii-nadtochii** [comment]
@alexander-yevsyukov I'm merging this PR. `lazyFmt(...)` will be added in a separate one.

**Pull request merged**
